/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.javanunes.Ferra;

import javax.swing.JOptionPane;

/**
 *
 * @author ricardo
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        setResizable(false);
        congelaBotoes(true);
    }
    
    public static void alert(String mensagem){
        JOptionPane.showMessageDialog(null,mensagem);
    }
   
    public static void print(Object mensagem){
        System.out.print(mensagem);
    }
    
     public static void status(String mensagem){
        lbStatus.setText(mensagem);
     } 
     
     public static String getCanal(){
       return cbxCanal.getSelectedItem().toString();
     } 
     
     public static String getPlacaRede(){
          return  cbxInterfaces.getSelectedItem().toString();
     }
     
     public static String getInterface(){
          return  cbxInterfaces.getSelectedItem().toString();
     }
     
     private void mudaMacAddressPraVagaba(){
         txtMacaddress.setText("F4:54:20:0B:6E:C3");         
     }
    
     public static String getMac(){
       return txtMacaddress.getText();
     } 
     
     public static String getPorta(){
       return txtPorta.getText();
     } 
   
     public static String getIp(){
       return txtIp.getText();
     } 
     
     public static String getCategoriaArtefato(){
       return cbxArtefato.getSelectedItem().toString();
     }
     
     public void congelaBotoes(boolean sim){
        if(sim){
            btAtacar.setEnabled(false);
            btAiroDumpMonitor.setEnabled(false);
            btRestaurar.setEnabled(false);
        }
        else{
            btAtacar.setEnabled(true);
            btAiroDumpMonitor.setEnabled(true);
            btRestaurar.setEnabled(true);
        }
     }
     
     public static void abreForm(){
          /* Create and display the form */
        if(!Controller.isRoot()){
            alert("Esse programa só roda com todo o seu potencial quando chamado por root! Tente o sudo.");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
     }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbStatus = new javax.swing.JLabel();
        lbInterface = new javax.swing.JLabel();
        cbxInterfaces = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtPorta = new javax.swing.JTextField();
        lbmacAddress = new javax.swing.JLabel();
        txtMacaddress = new javax.swing.JTextField();
        lbIp = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        lbCanal = new javax.swing.JLabel();
        cbxCanal = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        lbUsarMacVagaba = new javax.swing.JLabel();
        ckbUsarMacVagaba = new javax.swing.JCheckBox();
        lbMandarTexto = new javax.swing.JLabel();
        txtMandarTexto = new javax.swing.JTextField();
        lbGerarArtefato = new javax.swing.JLabel();
        cbxArtefato = new javax.swing.JComboBox<>();
        btGerarArtefato = new javax.swing.JToggleButton();
        btPreparar = new javax.swing.JButton();
        javax.swing.JToggleButton btWifiteMonitor = new javax.swing.JToggleButton();
        btAtacar = new javax.swing.JToggleButton();
        btBloqueia = new javax.swing.JButton();
        btDesbloqueia = new javax.swing.JToggleButton();
        btAiroDumpMonitor = new javax.swing.JButton();
        btRestaurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbStatus.setText("Info...");

        lbInterface.setText("INTERFACE:");

        cbxInterfaces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "wlp4s0", "wlp2s0", "wlo1", "wlo2", "wlo3", "run0", "wlan", "wlan1", "wlan0", "wlan0mon", "wlan1mon", "wlxc83a35cdb6", "enp1s0", " ", " " }));

        jLabel1.setText("PORTA:");

        txtPorta.setText("12345");
        txtPorta.setToolTipText("");
        txtPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortaActionPerformed(evt);
            }
        });

        lbmacAddress.setText("MAC:");

        txtMacaddress.setText("24:24:24:24:B1:3A");
        txtMacaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMacaddressActionPerformed(evt);
            }
        });

        lbIp.setText("IP:");

        txtIp.setText("104.105.136.48");
        txtIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpActionPerformed(evt);
            }
        });

        lbCanal.setText("CANAL:");

        cbxCanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", " " }));

        lbUsarMacVagaba.setText("USAR MAC DA VAGABA ->");

        ckbUsarMacVagaba.setText("SIM!");
        ckbUsarMacVagaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbUsarMacVagabaActionPerformed(evt);
            }
        });

        lbMandarTexto.setText("MANDAR TEXTO:");

        txtMandarTexto.setText("Vai pra ptqp!");

        lbGerarArtefato.setText("GERAR ARTEFATO: ");

        cbxArtefato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "windows/meterpreter/reverse_tcp", "windows/meterpreter/reverse_udp", "linux/meterpreter/reverse_tcp", "linux/meterpreter/reverse_udp", "macosx/meterpreter/reverse_tcp" }));

        btGerarArtefato.setText("GERAR ARTEFATO");
        btGerarArtefato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarArtefatoActionPerformed(evt);
            }
        });

        btPreparar.setText("PREPARAR");
        btPreparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrepararActionPerformed(evt);
            }
        });

        btWifiteMonitor.setText("WIFITE MONITOR");
        btWifiteMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btWifiteMonitorActionPerformed(evt);
            }
        });

        btAtacar.setText("ATACAR");
        btAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtacarActionPerformed(evt);
            }
        });

        btBloqueia.setText("BLOQUEIA");
        btBloqueia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBloqueiaActionPerformed(evt);
            }
        });

        btDesbloqueia.setText("DESBLOQUEIA");
        btDesbloqueia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesbloqueiaActionPerformed(evt);
            }
        });

        btAiroDumpMonitor.setText("MONITOR AIRODUMP");
        btAiroDumpMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAiroDumpMonitorActionPerformed(evt);
            }
        });

        btRestaurar.setText("RESTAURAR NET");
        btRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRestaurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btBloqueia)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btPreparar)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btGerarArtefato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDesbloqueia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btWifiteMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAiroDumpMonitor)
                .addGap(18, 18, 18)
                .addComponent(btAtacar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRestaurar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbGerarArtefato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxArtefato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbUsarMacVagaba)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ckbUsarMacVagaba)
                            .addGap(32, 32, 32)
                            .addComponent(lbMandarTexto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMandarTexto))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbInterface)
                            .addGap(6, 6, 6)
                            .addComponent(cbxInterfaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbmacAddress)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMacaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbIp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbCanal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbxCanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInterface)
                    .addComponent(cbxInterfaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbmacAddress)
                    .addComponent(txtMacaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIp)
                    .addComponent(txtIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCanal)
                    .addComponent(cbxCanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsarMacVagaba)
                    .addComponent(ckbUsarMacVagaba)
                    .addComponent(lbMandarTexto)
                    .addComponent(txtMandarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGerarArtefato)
                    .addComponent(cbxArtefato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBloqueia)
                    .addComponent(btDesbloqueia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPreparar)
                    .addComponent(btGerarArtefato)
                    .addComponent(btWifiteMonitor)
                    .addComponent(btAtacar)
                    .addComponent(btAiroDumpMonitor)
                    .addComponent(btRestaurar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortaActionPerformed

    private void txtIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIpActionPerformed

    private void ckbUsarMacVagabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbUsarMacVagabaActionPerformed
        // TODO add your handling code here:
        mudaMacAddressPraVagaba();
    }//GEN-LAST:event_ckbUsarMacVagabaActionPerformed

    private void btGerarArtefatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarArtefatoActionPerformed
        // TODO add your handling code here:
        Controller.gerarArtefatoExe();
    }//GEN-LAST:event_btGerarArtefatoActionPerformed

    private void btBloqueiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBloqueiaActionPerformed
        // TODO add your handling code here:
        Controller.bloqueiaIP(txtIp.getText());
    }//GEN-LAST:event_btBloqueiaActionPerformed

    private void btDesbloqueiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesbloqueiaActionPerformed
        // TODO add your handling code here:
         Controller.desbloqueiaIP(txtIp.getText());
    }//GEN-LAST:event_btDesbloqueiaActionPerformed

    private void btWifiteMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btWifiteMonitorActionPerformed
        // TODO add your handling code here:
        Controller.executa("wifite", true, true);
    }//GEN-LAST:event_btWifiteMonitorActionPerformed

    private void btPrepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrepararActionPerformed
        // TODO add your handling code here:
        Controller.prepararPlacasParaAtaqueMonitoramento();
        congelaBotoes(false);
    }//GEN-LAST:event_btPrepararActionPerformed

    private void btAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtacarActionPerformed
        // TODO add your handling code here:
        Controller.atacar();
    }//GEN-LAST:event_btAtacarActionPerformed

    private void txtMacaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMacaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMacaddressActionPerformed

    private void btAiroDumpMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAiroDumpMonitorActionPerformed
        // TODO add your handling code here:
        Controller.monitorWifiAirodump();
    }//GEN-LAST:event_btAiroDumpMonitorActionPerformed

    private void btRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRestaurarActionPerformed
        // TODO add your handling code here:
        congelaBotoes(true);
        Controller.restaurarConexoesWifi();
    }//GEN-LAST:event_btRestaurarActionPerformed

 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAiroDumpMonitor;
    private javax.swing.JToggleButton btAtacar;
    private javax.swing.JButton btBloqueia;
    private javax.swing.JToggleButton btDesbloqueia;
    private javax.swing.JToggleButton btGerarArtefato;
    private javax.swing.JButton btPreparar;
    private javax.swing.JButton btRestaurar;
    public static javax.swing.JComboBox<String> cbxArtefato;
    public static javax.swing.JComboBox<String> cbxCanal;
    public static javax.swing.JComboBox<String> cbxInterfaces;
    private javax.swing.JCheckBox ckbUsarMacVagaba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbCanal;
    private javax.swing.JLabel lbGerarArtefato;
    private javax.swing.JLabel lbInterface;
    private javax.swing.JLabel lbIp;
    private javax.swing.JLabel lbMandarTexto;
    public static javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbUsarMacVagaba;
    private javax.swing.JLabel lbmacAddress;
    public static javax.swing.JTextField txtIp;
    public static javax.swing.JTextField txtMacaddress;
    public static javax.swing.JTextField txtMandarTexto;
    public static javax.swing.JTextField txtPorta;
    // End of variables declaration//GEN-END:variables

}
